version: '3'
services:
    web:
        image: nginx:alpine
        container_name: ${PROJECT_NAME}_nginx
        volumes:
            - "./.etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./.etc/ssl:/etc/ssl"
            - "./bedrock:/var/www/html"
            - "./.etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        ports:
            - "80:80"
            - "3000:443"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
#        restart: always
        depends_on:
            - php
            - mysqldb
    php:
        build: ./php
        container_name: ${PROJECT_NAME}_php
#        restart: always
        volumes:
            - "./.etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./bedrock:/var/www/html"
            - "./.etc/.gitconfig:/var/www/.gitconfig"
            - ./.etc/.gitignore_global:/home/www-data/.gitignore_global
            - ./.etc/.gitconfig:/home/www-data/.gitconfig
            - ./.etc/.bashrc:/home/www-data/.bashrc


    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: ${PROJECT_NAME}_myadmin
        ports:
            - "8080:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${MYSQL_HOST}
              # restart: always
        depends_on:
            - mysqldb
    mysqldb:
        image: mysql:${MYSQL_VERSION}
        container_name: ${PROJECT_NAME}_mysql
        #   restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "8989:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
